In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('D:/Research Working Folder/Paper_1-Mobile Sensing Virtual Environment/static_50cm.csv', header=3)

In [3]:
axisX=data[' Z [ m ]']
axisY=data['X [ m ]']
axisZ=data[' Y [ m ]']

data.drop(labels=['X [ m ]'], axis=1, inplace=True)
data.drop(labels=[' Y [ m ]'], axis=1, inplace=True)
data.drop(labels=[' Z [ m ]'], axis=1, inplace=True)

data.insert(0, 'X', axisX)
data.insert(1, 'Y', axisY)
data.insert(2, 'Z', axisZ)

data.rename(columns={' Temperature [ K ]':'0.0'}, inplace=True)

In [4]:
stepsize=1.0

for i in range(2400):
    a=data['0.0']
    a.name='{}'.format((i+1)*stepsize)
    data=pd.concat([data, a],axis=1)

In [5]:
data

,X,Y,Z,0.0,1.0,2.0,3.0,4.0,5.0,6.0,...,2391.0,2392.0,2393.0,2394.0,2395.0,2396.0,2397.0,2398.0,2399.0,2400.0
0,-0.258711,0.000000,0.5,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854,...,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854,300.237854
1,0.309477,0.000000,0.5,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934,...,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934,300.688934
2,0.310122,0.100658,0.5,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900,...,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900,300.597900
3,-0.267367,0.097055,0.5,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996,...,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996,300.145996
4,0.938231,0.000000,0.5,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418,...,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418,301.322418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13893,58.326363,22.450001,0.5,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271,...,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271,301.077271
13894,58.551903,22.450001,0.5,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925,...,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925,301.010925
13895,57.949913,22.443819,0.5,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334,...,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334,301.198334
13896,57.949120,22.450001,0.5,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665,...,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665,301.193665
13897,57.616486,22.450001,0.5,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970,...,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970,300.831970

In [6]:
data.to_csv('D:/Research Working Folder/Paper_1-Mobile Sensing Virtual Environment/static_50cm_DEMO_new.csv', index=False)

In [68]:
import os

In [69]:
path='D:/CFD/AcaBuilding_transient_files/user_files'
path_list=os.listdir(path)

In [72]:
path_list

['export.csv',
 'FLU.png',
 'FLU.wmv',
 'FLU2.png',
 'Geom.png',
 'Geom_plane.png',
 't_0.csv',
 't_1.csv',
 't_2.csv',
 't_3.csv',
 't_4.csv',
 't_5.csv',
 't_6.csv',
 't_7.csv']

In [76]:
path+path_list[6]

'D:/CFD/AcaBuilding_transient_files/user_filest_0.csv'

In [79]:
data2=pd.read_csv(path+'/'+path_list[6], header=3)

In [80]:
data2

         X [ m ]   Y [ m ]    Z [ m ]   Temperature [ K ]
0       0.000000       0.5  -0.258711          300.000671
1       0.000000       0.5   0.309477          300.001709
2       0.100658       0.5   0.310122          300.002625
3       0.097055       0.5  -0.267367          300.001099
4       0.000000       0.5   0.938231          300.001526
...          ...       ...        ...                 ...
13893  22.450001       0.5  58.326363          300.000580
13894  22.450001       0.5  58.551903          300.000580
13895  22.443819       0.5  57.949913          300.000732
13896  22.450001       0.5  57.949120          300.000671
13897  22.450001       0.5  57.616486          300.000610

[13898 rows x 4 columns]

In [ ]:
stepsize=1.0

for i in range(2000):
    data=pd.read_csv()
    a=data[' Temperature [ K ]']
    a.name='{}'.format((i+1)*stepsize)
    data=pd.concat([data, a],axis=1)